version: "2.2"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        cpus: 1
        environment:
            - "TTS_GLOW_TTS=3511"
            - "TTS_MULTIBAND_MELGAN=667775"
            - "TTS_DEBUG=1"
        volumes:
            - "./data/src/flask:/content/src/flask"
            - "./data/models:/content/models"
        ports: 
            - "5000:5000"